# fly.toml app configuration file generated for apogamma on 2025-04-14T14:56:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apogamma'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.domains]]
    name = "apogamma.org"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1